//postReview & postReviewReducer Folders
export const CHANGE_REVIEW_BODY = 'CHANGE_REVIEW_BODY';
export const CHANGE_REVIEW_CHARACTERISTICS = 'CHANGE_REVIEW_CHARACTERISTICS';
export const CHANGE_REVIEW_EMAIL = 'CHANGE_REVIEW_EMAIL';
export const CHANGE_REVIEW_MODAL = 'CHANGE_REVIEW_MODAL';
export const CHANGE_REVIEW_PHOTOS = 'CHANGE_REVIEW_PHOTOS';
export const CHANGE_REVIEW_RATING = 'CHANGE_REVIEW_RATING';
export const CHANGE_REVIEW_RECOMMENDATION = 'CHANGE_REVIEW_RECOMMENDATION';
export const CHANGE_REVIEW_SUMMARY = 'CHANGE_REVIEW_SUMMARY';
export const CHANGE_REVIEW_USER = 'CHANGE_REVIEW_USER';
export const CHANGE_REVIEW_WORD_COUNT = 'CHANGE_REVIEW_WORD_COUNT';

//productRatings & productRatingsReducer Folders
export const CHANGE_PRODUCT_AVG_RATING = 'CHANGE_PRODUCT_AVG_RATING';
export const CHANGE_PRODUCT_AVG_STAR_RATING = 'CHANGE_PRODUCT_AVG_STAR_RATING';
export const CHANGE_PRODUCT_CHARACTERISTICS = 'CHANGE_PRODUCT_CHARACTERISTICS';
export const CHANGE_PRODUCT_RATINGS = 'CHANGE_PRODUCT_RATINGS';
export const CHANGE_PRODUCT_RECOMMENDED = 'CHANGE_PRODUCT_RECOMMENDED';
export const CHANGE_RATINGS_FILTER = 'CHANGE_RATINGS_FILTER';
export const RESET_RATINGS_FILTER = 'RESET_RATINGS_FILTER';

//reviewsList & reviewsListReducer Folders
export const CHANGE_REVIEW_DISPLAY_LIMITER = 'CHANGE_REVIEW_DISPLAY_LIMITER';
export const CHANGE_REVIEW_FEEDBACK = 'CHANGE_REVIEW_FEEDBACK';
export const CHANGE_REVIEW_IMAGE_MODAL = 'CHANGE_REVIEW_IMAGE_MODAL';
export const CHANGE_REVIEW_SCROLL = 'CHANGE_REVIEW_SCROLL';
export const CHANGE_REVIEWS_LIST = 'CHANGE_REVIEWS_LIST';
export const CHANGE_REVIEW_SORT = 'CHANGE_REVIEW_SORT';